lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    # TODO: Test JWT Authentication op API via POSTMAN
    # TODO: Zorg dat de JWT Token opgeslagen wordt
    # TODO: Zorg er voor dat de JWT Authentication slechts op een deel van de API werkt
    token_ttl: 3600
