#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
  path: /login_check
  methods: ['POST']

api_gym_login:
  path: /gym_login
  methods: ['POST']
  controller: App\Controller\Api\TwoFactorLogin\GymLoginController

# Login route
#login:
#  path:       /login
#  controller: App\Controller\SecurityController::login
#  methods: POST

# Refresh route
gesdinet_jwt_refresh_token:
  path: /token/refresh
  methods: ['POST']
  controller: gesdinet.jwtrefreshtoken::refresh

generate_twoFactorCode:
  path: /api/generate_2fa
  methods: ['GET']
  controller: App\Controller\Api\TwoFactorLogin\CodeGeneratorController

addWorkout:
  path: /api/addWorkout
  methods: ['POST']
  controller: App\Controller\Api\ChooseWorkout