#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
  path: /login_check
  methods: ['POST']

# Login route
#login:
#  path:       /login
#  controller: App\Controller\SecurityController::login
#  methods: POST

# Refresh route
gesdinet_jwt_refresh_token:
  path: /token/refresh
  methods: ['POST']
  controller: gesdinet.jwtrefreshtoken::refresh
